### ISSUE TITLE
Migrate the pylint's configuration file (``.pylintrc`` and ``pylintrc``)

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [abravalheri/ini2toml#52]
Thank you for this project, someone opened a merge request in astroid using it (https://github.com/PyCQA/astroid/pull/1789) and this looks great.

I realized that the pylint configuration file (that are ini even if they have a specific name) are not migrated, I think this would be a cool feature.

**Comment by Pierre-Sassoulas** [comment]
Closing because it can be done manually, sorry for the noise.

**Comment by abravalheri** [comment]
> Closing because it can be done manually, sorry for the noise.

Hi @Pierre-Sassoulas, when you say that it can be done manually, does it mean that `ini2toml pylintrc` will generate the wrong output and needs to be corrected or is it the case that the [`best-effort`](https://github.com/abravalheri/ini2toml/blob/main/src/ini2toml/plugins/best_effort.py) plugin is enough but only the input file name needs change?

If the output needs to be corrected, it would be necessary to implement a new [plugin](https://github.com/abravalheri/ini2toml/tree/main/src/ini2toml/plugins) for pylint.

**Comment by Pierre-Sassoulas** [comment]
I did not read what the project was doing properly, the output is good and I thought ini2toml detected ini files to be upgraded and missed pylint (but in fact a contributor was doing that). So it's my bad :)
