### ISSUE TITLE
Pulling metadata out of setup.py

### ISSUE THREAD

**Issue by cclauss** [abravalheri/ini2toml#54]
I love this tool because it greatly simplifies the migration into `pyproject.toml`.  One problem that remains in these conversions is migrating the metadata from `setup.py` files.  Is there some tool that would migrate `setup.py` metadata` into `setup.cfg` that could act as a preprocess before doing an ini2toml migration?  The goal of these PEPs is to have a minimal or preferably no `setup.py` file so migrating this metadata is key.

Perhaps https://github.com/gvalkov/setuptools-py2cfg

**Comment by abravalheri** [comment]
Hi @cclauss, `setuptools-py2cfg` seems to fit this niche. There is also [akx/setuppy2cfg](https://github.com/akx/setuppy2cfg) which is only starting.
However, since `setup.py` can be arbitrarily dynamic, I would not be surprised if both tools have edge cases...
