### ISSUE TITLE
`install_requires = file: requirements.txt` converted to `dependencies = ["file: requirements.txt"]`

### ISSUE THREAD

**Issue by graingert** [abravalheri/ini2toml#71]
setuptools supports `file:` directives for reading requirements see https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#opt-6

**Comment by abravalheri** [comment]
Hi @graingert, thank you very much for opening this issue.

The `file:` directive for requirements was a late addition to setuptools and is not implemented yet in `ini2toml`. I will have a look once I have time, but if any member of the community would like to give it a go and beat me to that, PRs are welcome.

**Comment by abravalheri** [comment]
Meanwhile (when this missing piece is not implemented -- it might take me a while), if you want to manually add this manually you can add something like:

```toml
[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}
```

Ref: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata

**Comment by graingert** [comment]
@abravalheri can you cut a release with this in?
